
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Caffe
{

using System;
    using System.Collections.Generic;
    
public partial class C6Menu
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public C6Menu()
    {

        this.C6OrderMenu = new HashSet<C6OrderMenu>();

    }


    public int MenuID { get; set; }

    public string Name { get; set; }

    public Nullable<decimal> Cost { get; set; }

    public Nullable<int> Discount { get; set; }

    public string Description { get; set; }

    public Nullable<int> Weight { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<C6OrderMenu> C6OrderMenu { get; set; }

}

}
