
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Caffe
{

using System;
    using System.Collections.Generic;
    
public partial class C6Shift
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public C6Shift()
    {

        this.C6ShiftReporting = new HashSet<C6ShiftReporting>();

    }


    public int ShiftID { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public Nullable<System.TimeSpan> StartTime { get; set; }

    public Nullable<System.TimeSpan> EndTime { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<C6ShiftReporting> C6ShiftReporting { get; set; }

}

}
