
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Caffe
{

using System;
    using System.Collections.Generic;
    
public partial class C6ShiftReporting
{

    public int ShiftReportingID { get; set; }

    public Nullable<int> UserID { get; set; }

    public Nullable<int> ShiftID { get; set; }

    public Nullable<System.TimeSpan> StartTimeFact { get; set; }

    public Nullable<System.TimeSpan> EndTimeFact { get; set; }

    public Nullable<int> Turnout { get; set; }



    public virtual C6Shift C6Shift { get; set; }

    public virtual C6Tornout C6Tornout { get; set; }

    public virtual C6User C6User { get; set; }

}

}
